# Generated by Django 4.2.1 on 2023-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kisi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kproduct",
            options={},
        ),
        migrations.AddField(
            model_name="kproduct",
            name="image",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="kproduct",
            name="name",
            field=models.CharField(default="name", max_length=100),
        ),
        migrations.AddField(
            model_name="kproduct",
            name="price",
            field=models.CharField(default="0.00", max_length=100),
        ),
        migrations.AddField(
            model_name="kproduct",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kproduct",
            name="tag",
            field=models.CharField(default="All,", max_length=1000),
        ),
        migrations.AddField(
            model_name="kproduct",
            name="type",
            field=models.CharField(default="Cake", max_length=20),
        ),
        migrations.AddField(
            model_name="kreview",
            name="rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="kreview",
            name="text",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="kproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
