# Generated by Django 4.2.1 on 2023-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kisi", "0002_alter_kproduct_options_kproduct_image_kproduct_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kproduct",
            name="image",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
