# Generated by Django 4.2.1 on 2023-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kisi", "0005_alter_kreview_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="kreview",
            name="owner",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
