# Generated by Django 4.2.1 on 2023-05-10 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_customer_staff_staffprofile_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="expiry_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="code expired"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="prev_code",
            field=models.IntegerField(default=0),
        ),
    ]
