# Generated by Django 4.2.1 on 2023-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_user_code_user_expiry_date_user_prev_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expiry_date",
            field=models.DateTimeField(auto_now=True, verbose_name="code expired"),
        ),
    ]
