# Generated by Django 4.2.1 on 2023-05-25 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0005_alter_user_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 25, 16, 49, 28, 830043),
                verbose_name="code expired",
            ),
        ),
    ]
