# Generated by Django 4.2.1 on 2023-06-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0019_alter_user_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 2, 10, 5, 58, 54478, tzinfo=datetime.timezone.utc
                ),
                verbose_name="code expired",
            ),
        ),
    ]
