# Generated by Django 4.2.1 on 2023-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
