# Generated by Django 4.2.1 on 2023-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0005_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("UNCATEGORISED", "UnCategorized")],
                default="UNCATEGORISED",
                max_length=50,
            ),
        ),
    ]
