# Generated by Django 4.2.1 on 2023-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0007_banner_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
