# Generated by Django 4.2.1 on 2023-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0008_tag_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="StoreAPI.tag"),
        ),
    ]
