# Generated by Django 4.2.1 on 2023-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0010_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
