# Generated by Django 4.2.1 on 2023-06-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0011_product_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "District",
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StoreAPI.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Division",
            },
        ),
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StoreAPI.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "parish",
                "verbose_name_plural": "parish",
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StoreAPI.parish",
                    ),
                ),
            ],
            options={
                "verbose_name": "village",
                "verbose_name_plural": "village",
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("isActive", models.BooleanField(default=False)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StoreAPI.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "street",
                "verbose_name_plural": "street",
            },
        ),
    ]
