# Generated by Django 4.2.1 on 2023-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0013_usertoken_order_orderproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="address",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="email",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="password",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="phoneNumber",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
