# Generated by Django 4.2.1 on 2023-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0014_alter_usertoken_address_alter_usertoken_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="contactName",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CheckOut", "CheckOut"),
                    ("Placed", "Placed"),
                    ("Processed", "Processed"),
                    ("Delivered", "Delivered"),
                    ("Completed", "Completed"),
                ],
                default="CheckOut",
                max_length=20,
            ),
        ),
    ]
