# Generated by Django 4.2.1 on 2023-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0015_order_date_updated_alter_order_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="availability",
        ),
        migrations.AddField(
            model_name="product",
            name="dealPoints",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="deliveryPoints",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="recomPoints",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="section",
            field=models.CharField(default="ALL", max_length=100),
        ),
    ]
