# Generated by Django 4.2.1 on 2023-06-07 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0016_remove_product_availability_product_dealpoints_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="deliveryPoints",
        ),
    ]
