# Generated by Django 4.2.1 on 2023-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreAPI", "0017_remove_product_deliverypoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deliveryPoints",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="inStock",
            field=models.BooleanField(default=False),
        ),
    ]
